// Audited UI revision. This file is integrated inside app.js's state closure.
const modes=[['cooperate','专业分工 · 组长轮询'],['challenge','材料交叉质询'],['mixed','先协作后对抗'],['group_cooperate','分组协作'],['group_debate','分组对抗'],['reflection','生生互评与反思']];
const dimensions=[['values_alignment','思政融入'],['disciplinary_accuracy','专业准确性'],['evidence_use','证据使用'],['question_quality','质疑质量'],['response_quality','回应质量'],['collaboration','协作贡献'],['reflection_revision','反思修订']];
let modeChoice='cooperate', groupChoice=3, roundChoice=12, composerAt=null, expanded=false;
const homePrevious=pages.home;
pages.home=()=>homePrevious().replace('<h3>教研','<h3>教学研讨').replace('</button><button class="portal classroom"','</button><button class="portal classroom"').replace('</button><button class="portal classroom"','</button><button class="portal classroom"');
const homeBase=pages.home;
pages.home=()=>{let h=homeBase();const marker='<button class="portal classroom"';const bridge=`<section class="module-bridge"><span class="eyebrow">PLAN EXCHANGE</span><h3>教学研讨 ⇄ 模拟课堂</h3><label>选择来源方案<select id="exchange-plan">${s.artifacts.map(a=>`<option value="${a.artifact_id}">${a.scene==='seminar'?'教学研讨':'模拟课堂'} · ${esc(a.title)}</option>`).join('')||'<option value="">暂无方案</option>'}</select></label><button id="exchange" class="primary" ${s.artifacts.length?'':'disabled'}>导入另一模块</button><small>创建新版本，保留原方案</small><details><summary>双向流转记录（${s.transfers.length}）</summary>${s.transfers.map(t=>`<p>${t.from_scene==='seminar'?'教学研讨 → 模拟课堂':'模拟课堂 → 教学研讨'}<br>${esc(t.time)}</p>`).join('')||'暂无流转'}</details></section>`;return h.replace(marker,bridge+marker)};
const dashPrevious=dashboard;
dashboard=function(scene,r){let h=dashPrevious(scene,r).replaceAll('参与教研','参与教学研讨').replace('教研 · 数据驾驶舱','教学研讨 · 数据驾驶舱');const play=/<button id="play">[\s\S]*?<\/button>/;const playback=h.match(play)?.[0]||'';h=h.replace(play,'').replace('<button id="expand-screen">',playback+'<button id="expand-screen">');const frozen=r?.status==='running';h=h.replace('<div class="cockpit-grid">',`<div class="mode-settings"><label>研讨模式<select id="mode-choice" ${frozen?'disabled':''}>${modes.map(([id,label])=>`<option value="${id}" ${(r?.interaction_mode||modeChoice)===id?'selected':''}>${label}</option>`).join('')}</select></label><label>小组数<input id="group-choice" type="number" min="2" max="12" value="${r?.group_count||groupChoice}" ${frozen?'disabled':''}></label><label>演示轮次<input id="round-choice" type="number" min="4" max="60" value="${r?.settings_snapshot.max_rounds||roundChoice}" ${frozen?'disabled':''}></label><small>运行中固定配置；结束后可调整</small></div><div class="cockpit-grid">`);const ev=r?s.events.filter(e=>e.run_id===r.run_id):[],last=ev.at(-1),names=scene==='seminar'?['教研组长','教学设计','专业教师','思政教师']:['教师','学习者A','学习者B','小组代表'];h=h.replace('<div class="cockpit-actions">',`<div class="exchange-stage">${names.map((n,i)=>`<div class="cast ${last?.speaker_index===i?'speaks':''}">${YanzhiPortrait(i+4)}<b>${n}</b><small>${last?.speaker_index===i?'正在发言':'倾听'}</small></div>`).join('<span class="exchange-line">↔</span>')}<p>${esc(last?.task_role||'等待组长启动讨论')}</p></div><div class="cockpit-actions">`);h=h.replace('id="participate"','id="participate" aria-label="参与对话"');return h;};
const scenePrevious=scenePage;
scenePage=function(scene,title){return scenePrevious(scene,scene==='seminar'?'教学研讨':title).replace('<details class="scene-details"><summary>人物与场景', '<details class="scene-details"><summary>人物与场景')+`<details class="scene-details"><summary>七维量规 · 人工评价</summary><p>探索性草案；0—4等级，空值为未评。不是已验证量表。</p><form id="dimension-form"><label>事件<select name="event_id" required>${s.events.filter(e=>e.scene===scene).map(e=>`<option value="${e.event_id}">${e.sequence} · ${esc(e.actor_code)} · ${esc(e.text.slice(0,35))}</option>`).join('')}</select></label><div class="fields">${dimensions.map(([id,label])=>`<label>${label}<select name="${id}"><option value="">未评</option>${[0,1,2,3,4].map(v=>`<option>${v}</option>`).join('')}</select></label>`).join('')}</div><label>评价者编码<input name="rater" required placeholder="如 R01"></label><label>证据与理由<textarea name="note"></textarea></label><button class="primary">保存逐维评分</button></form></details>`;};
const exportPrevious=pages.export;
pages.export=()=>exportPrevious().replace('<div class="fields">',`<div class="export-definition"><h3>导出字段与测量边界</h3><table><tr><th>文件</th><th>包括什么</th></tr><tr><td>runs / metrics</td><td>运行起止、墙钟时长、模式、分组、各类事件计数</td></tr><tr><td>events</td><td>发言人、时间、间隔、回应延迟、输入框停留时长、回复链、目标、分工与分组</td></tr><tr><td>artifacts / transfers</td><td>方案正文、父版本、输入快照及双向导入记录</td></tr><tr><td>ratings / rubric</td><td>七维人工分数、依据、评价者、修订链、分级锚点</td></tr></table><p>真实学习时间、认知投入、语音时长与学习增益：尚未采集。运行墙钟时间包含暂停，不能替代学习时间。</p></div><div class="fields">`);
ensureRun=function(scene){let r=run(scene);if(r?.status==='running')return r;let p=plans(scene).find(a=>a.artifact_id===selected[scene])||plans(scene).at(-1);if(!p)p=api.artifact(s,{scene,title:'AI质检与工程责任 · 预设案例',content:'核查模型判断、缺陷后果、复检条件与责任主体。'});s.settings.interaction_mode=modeChoice;s.settings.group_count=groupChoice;s.settings.max_rounds=roundChoice;s.settings.rubric_version='七维草案-v1';return api.start(s,scene,p.artifact_id);};
nextEvent=function(scene){const r=ensureRun(scene);if(r.demo_step>=r.settings_snapshot.max_rounds){stopPlayback();msg('已达到本次演示轮次上限。');render();return;}const k=r.demo_step++,phase=k%4,group='G'+(Math.floor(k/4)%r.group_count+1),prior=s.events.filter(e=>e.run_id===r.run_id).at(-1);const coop=[['主持','question','请依专业分工轮询：目标设计、专业案例、价值讨论。'],['教学设计','assertion','我负责课件的学习目标，要求学生比较自动放行和人工复检。'],['专业案例','assertion','我负责缺陷后果与适用条件，标明待核查参数。'],['价值讨论','revision','我补充工程责任分工，并把组内成果整合成课件提纲。']];const challenge=[['材料提交','assertion','待审材料主张：准确率达标即可自动放行。'],['专业质询','critique','请说明漏检的后果与人工复检条件；总体准确率不能支持这个结论。'],['证据回应','response','材料尚未提供这些条件，需要收窄结论并保留待查项。'],['反思修订','revision','修订为：只有核验应用边界与风险控制后才能讨论放行。']];const reflect=[['自我反思','assertion','我曾把模型结果等同于安全结论。'],['同伴质询','critique','这个判断缺少适用范围与后果分析。'],['同伴回应','response','我接受这个质疑，补充人工复检依据。'],['反思修订','revision','将事实、推断和未知分开，记录此次修改理由。']];const m=r.interaction_mode,seq=m==='reflection'?reflect:(m==='challenge'||m==='group_debate'||m==='mixed'&&k>=4)?challenge:coop,d=seq[phase],names=scene==='seminar'?['教研组长','教学设计','专业教师','思政教师']:['教师','学习者A','学习者B','小组代表'];const e=api.event(s,r.run_id,{source:'demo',actor_code:(m.startsWith('group')?group+' · ':'')+names[phase],kind:d[1],text:d[2],reply_to:prior?.event_id||null,group_id:m.startsWith('group')?group:null,target_actor:prior?.actor_code||null,task_role:d[0],interaction_mode:m,evidence_reference:'内置脚本示例；不是对导入材料的模型分析'});e.speaker_index=phase;render();};
bindDashboard=function(){const on=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{stopPlayback();page=b.dataset.page;expanded=false;lastBundle=null;render()});const feed=document.getElementById('live-feed');if(feed){if(followLive)feed.scrollTop=feed.scrollHeight;feed.onscroll=()=>{followLive=feed.scrollHeight-feed.scrollTop-feed.clientHeight<40};on('follow-live',()=>{followLive=true;feed.scrollTop=feed.scrollHeight});}
const screen=document.getElementById('cockpit');if(screen)screen.classList.toggle('expanded',expanded);on('expand-screen',()=>{expanded=!expanded;screen.classList.toggle('expanded',expanded)});
for(const [id,fn]of [['mode-choice',v=>modeChoice=v],['group-choice',v=>groupChoice=Math.max(2,Math.min(12,Number(v)||3))],['round-choice',v=>roundChoice=Math.max(4,Math.min(60,Number(v)||12))]]){const el=document.getElementById(id);if(el)el.onchange=()=>fn(el.value)}
on('play',()=>{if(ticker){stopPlayback();render();return;}autoScene=page;nextEvent(page);if(autoScene)ticker=setInterval(()=>{try{nextEvent(page)}catch(e){stopPlayback();msg(e.message,true)}},3000)});on('step',()=>{stopPlayback();nextEvent(page)});on('finish-session',()=>{stopPlayback();api.finish(s,run(page).run_id);render()});on('join',()=>{stopPlayback();composerAt=Date.now();const d=document.getElementById('participate');d.showModal();document.querySelector('#participate textarea').focus()});on('close-dialog',()=>document.getElementById('participate').close());
const f=document.getElementById('participation-form');if(f)f.onsubmit=e=>{e.preventDefault();const d=new FormData(f),text=String(d.get('message')).trim();if(!text)return;const r=ensureRun(page),prior=s.events.filter(x=>x.run_id===r.run_id).at(-1);const human=api.event(s,r.run_id,{source:'human_input',actor_code:'真人·'+d.get('role'),kind:'question',text,reply_to:prior?.event_id||null,input_duration_ms:composerAt?Date.now()-composerAt:null});const response=api.event(s,r.run_id,{source:'demo',actor_code:'主持人·预设回应',kind:'response',text:'你的发言已记录。请补充可核查依据，以及对应课件部分。此回应为固定预设，不是模型分析。',reply_to:human.event_id,target_actor:human.actor_code});response.speaker_index=0;document.getElementById('participate').close();followLive=true;render();};
on('exchange',()=>{const a=s.artifacts.find(x=>x.artifact_id===document.getElementById('exchange-plan').value);if(!a)return;const b=api.transferArtifact(s,a.artifact_id,a.scene==='seminar'?'classroom':'seminar',true);selected[b.scene]=b.artifact_id;msg('方案已导入另一模块，新旧版本均已保留。');render()});
const rf=document.getElementById('dimension-form');if(rf)rf.onsubmit=e=>{e.preventDefault();try{const d=new FormData(rf),scores={};dimensions.forEach(([id])=>scores[id]=d.get(id)===''?null:Number(d.get(id)));api.rate(s,{event_id:d.get('event_id'),rater_code:d.get('rater'),verdict:'not_assessed',score:null,rubric_scores:scores,note:d.get('note')});msg('七维评分已保存。');render()}catch(err){msg(err.message,true)}};
on('make-bundle',()=>{exportText=document.getElementById('include-text').value==='yes';exportScope=document.getElementById('export-scope').value;lastBundle=api.bundle(s,{includeText:exportText,scope:exportScope});render()});for(const id of ['include-text','export-scope']){const el=document.getElementById(id);if(el)el.onchange=()=>{exportText=document.getElementById('include-text').value==='yes';exportScope=document.getElementById('export-scope').value;lastBundle=null;render()}}on('zip-download',()=>download('yanzhi-research.zip',ResearchZip(lastBundle.files),'application/zip'));document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>download(b.dataset.file,lastBundle.files[b.dataset.file],'text/plain;charset=utf-8'));
};
